apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fw-gui-data-pvc
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-config-pvc
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
